### ISSUE TITLE
getTx 404ing without metadata

### ISSUE THREAD

**Issue by ivmidable** [MatterPool/TXQ#23]
The line below breaks getting TX Status for TXs that are missing optional metadata.
https://github.com/MatterPool/TXQ/blob/f721ed710d85acad5ded557b8e3a87e83cadf1cf/src/services/use_cases/tx/GetTx.ts#L26-L28

Changing it to below /seems/ to resolve the issue well enough.
```
    if (!txmeta) {
        txmeta = {};
    }
```

**Comment by attilaaf** [comment]
Thanks!

**Comment by attilaaf** [comment]
Fixing next release

**Comment by attilaaf** [comment]
Fixed in latest release.
